import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import { Heading } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SWEDISH TECHNOLOGY TEST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.title}>
          Welcome to
          <a href="https://swedishtechnology.com" color="brand.400">
            <Heading color="brand.400"> SWEDISH TECHNOLOGY</Heading>
          </a>
        </div>

        {/* <motion.div
          style={{
            width: "200px",
            height: "200px",
            backgroundColor: "blue",
          }}
          animate={{
            scale: [1, 2, 2, 1, 1],
            rotate: [0, 0, 180, 180, 0],
            borderRadius: ["0%", "0%", "50%", "50%", "0%"],
          }}
          transition={{
            duration: 2,
            ease: "easeInOut",
            times: [0, 0.2, 0.5, 0.8, 1],
            repeat: Infinity,
            repeatDelay: 1,
          }}
        /> */}
      </main>

      <footer className={styles.footer}></footer>
    </>
  );
};

export default Home;
